### PR TITLE
#10: Embark Store, List-support

### PR DESCRIPTION
**Pull request by oscarnylander**

### CODE REVIEW

**Comment by sampettersson** [comment]
Isn't the spec to flatten these? What happens with tracking, etc? 🤔

**Comment by StylianosGakis** [comment]
Maybe discuss this here https://hedviginsurance.slack.com/archives/C032XLLR963/p1645693202443489 to make sure it'd all work for all of us. It'd be nice to get some feedback on how web does it as well, which I assume is all Strings and lodash sets to modify them atm

**Comment by hedvigoscar** [comment]
It is on spec to flatten them, but I think the spec is constraining us in a bad way, for not enough benefit.

For tracking-purposes, I think we can probably flatten it on the call-site in order to maintain backwards compatibility.

**Comment by hedvigoscar** [comment]
Alternatively, we could break backwards compatibility with the tracking, if that's not too big of a deal for the analytics-team.

**Pull request closed without merging**
